### ISSUE TITLE
Encounter Dictionaries are Returning 'Travel-Only' Encounters during Rest Events

### ISSUE THREAD

**Issue by Spooky-Noodle** [Spooky-Noodle/Strahd-Travel-Manager#4]
Relevent Code:

```python
 if self.vistGuide == True: # Players traveling with Vistani guides
            encRoll = sRoll('1d12')
        else: # Players traveling alone
            encRoll = int(iRoll('1d12') + iRoll('1d8'))
        if self.areTravel == False: # Players are resting/camping
            if self.isNight == False: # Stationary during the day
                if encRoll != 4 or 5 or 6 or 9 or 10 or 15: # Not a travelling encounter
                    encRoll = str(encRoll)
                    self.recentEnc += 1 # Increases recent encounters
                    encounter = dayEncounters.get(encRoll) # Daytime Encounter
                    print("The players encounter " + encounter + ".") # Says what the players face
```

```python
dayEncounters = { #The possible encounters during the day; each item corresponds to an entry in my notes
    "2": sRoll('3d6') + " Barovian commoners",
    "3": sRoll('1d6') + " Barovian scouts",
    "4": "a Hunting trap",
    "5": "a Grave",
    "6": "a False trail",
    "7": str(iRoll('1d4') + 1)  + " Vistani bandits",
    "8": "a Skeletal rider",
    "9": "a Trinket",
    "10": "a Hidden bundle", 
    "11": ravens(),
    "12": sRoll('1d6') + " dire wolves",
    "13": sRoll('3d6') + " wolves",
    "14": sRoll('1d4') + " berserkers",
    "15": "a corpse",
    "16": sRoll('1d6') + " werewolves in human form",
    "17": "a druid with " + sRoll('2d6') + " twig blights",
    "18": sRoll('2d4') + " needle blights",
    "19": sRoll('1d6') + " scarecrows",
    "20": "a revenant"
}
```

```python
dayRest = timePeriod(areTravel = False, isNight = False)

dayRest.timeCheck()
```

Terminal Output: 

```Time spent resting during the day (in hours): 15
The players encounter a Skeletal rider.
The players encounter a corpse.
```

As you can see, the terminal returns `a corpse` as one of the encounters, however, `a corpse` is listed in the dictionary as entry 15, and `if encRoll != 4 or 5 or 6 or 9 or 10 or 15:` would seem to indicate that the program is only supposed to consult the dictionary if the resulting roll is **not** 4, 5, 6, 9, 10, or 15. 

I can't figure out why the program is returning travel-only encounters, when it's set not to proc. 

One possibility is that I don't have an `else` set in the code, for what to do when the encounter roll _is_ equal to one of those rolls. However, I would think that it would just pass to the rest of the code, so that's a little confusing.

**Comment by jaredly** [comment]
Try running `encRoll != 4 or 5 or 6 or 9 or 10 or 15` in the REPL, for various values of `encRoll`

**Comment by jaredly** [comment]
For "is x (not) one of these several options", I tend to use an array and the `in` operator. So in this case `if encRoll not in [4,5,6,9,10,15]:`

**Comment by Spooky-Noodle** [comment]
> Try running `encRoll != 4 or 5 or 6 or 9 or 10 or 15` in the REPL, for various values of `encRoll`

Forgive me, but what does `in the REPL` mean? Does that just mean to isolate that part of the code, and have it print out stuff whether it's recognizing the values? 

Also, I changed it to use the array format, `if encRoll not in [4,5,6,9,10,15]:` since that is much shorter, and looks cleaner.

**Comment by jaredly** [comment]
the REPL is what you get when you run `python` from the command line, when it gives you a `>>> ` and you can types stuff and see what it evaluates to. It's very nice for trying things out. (it's short for Read Eval Print Loop)
